travis:
  secure:
    BINSTAR_TOKEN: JcSZmPlG3DUMmuQSTK9juOyJTDSP746gz1Sc/yQW9gkqyfumaZ8DMj9QEcZl78i7SHBlks+BAHBbsRV5QhBOg6ZAmE63ASk57uWLZkOeKMOdnGNsBSl7QtlThhMgNI98DEo1Q4CxFeNdaPgqe3tqjWwl+nhk7eff5JzSe7vtANo+iVzTa/EHieYGyymjGxnAKAs8whEQNIgD9TlvHFVkMFe/NAf1zBPAZUSz1CiYn7HJyU6kcqu09UOUxzy8L5YX889Y8LEdJnjq8pETJi+lmsxqP7DZi3HAxSFd5Dd+4XUAZd6vMDWbHAXm0eQ1wjZg6PoSrv6ioMGp8+0NOsN7wKB2CVJex55+Rk58TelncOeCoaVMAT1fB89VT86+YUoGSgCGRh+DH6Ui43cp/sJzcoz6WQ2UNN/pxJqwq2i6Rnsj0DMVUaxXsTIEN/oEeNG6j0n0caGROg6MvHHcUSYuysENXhBTREqEHj5d4lAZnMQGOpn0xvN5O8/Sfk7I/WrU4XOFODknb7uuLbv6z6Os9C63p4crajhIftiLQBNKggvO5V7mNkWaKEschAsMxM+6ongZM+BqCwEVSPuBJP00FBi6HkcuM/vNxLDaFx1QQ4d9tjQmn7rnZ/NR5Hgls3mbFJOrcCmMRV/IRQ+lMcReOWDZDpQ+WKzj99AKMiYgtgY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: false
